### PR TITLE
#93 adding html and css to new viewings

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
is there a way to require an html file into another html file? for instance if i've already created the navigation bar and would like to basically display it on every page without adding the code to every page?

**Comment by sumeetjain** [comment]
You can add it to the **app/views/layouts/application.html.erb** page – that's like layout.erb in Sinatra.

You can also check out [partials](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials), which is how you can use snippets of HTML/ERB inside of other files.

**Comment by clburns107** [comment]
Why are my navigation links green? My global SCSS says they should be black.  

Also where do i find the HTML CSS files that allow me to alter the login page and logout link that Devise created?

The application file says <%= stylesheet_link_tag :application, media: "all" %> but then also says something about CSS overrides? is this the source of all my problems?

**Comment by halfghaninne** [comment]
Stepping through things right now. Navigation links on which views? Dashboard views?

**Comment by clburns107** [comment]
The navigation html is in the app/views/layouts/application.html.erb page 
which according to Sumeet will filter down to all the pages.

**Pull request merged**
