### PR TITLE
Adding theater name to Play

### PR DESCRIPTION
**Pull request by youcatastrophe**
So far I've added some ActiveRecord Associations for Plays and Theaters so Plays can access the Theater names. I've also run the 'rails generate administrate:views' command so that views for the Play Class can be modified, if need be. I'm now in the process of trying to figure out how to change forms so that they accept in a string (the Theater Name) BUT that the corresponding ID gets saved to the database. Also, we'll need to the Theater Name to show up instead of Theater_ID, anywhere it is referenced.

### CODE REVIEW

**Comment by halfghaninne** [comment]
Ryan, I'm sorry this reply took so long! I see that your models do not have Active Record associations, though your schema shows some artificial relationships with columns like `theatre_id` in the `plays` table.

I think creating these associations should automatically lead to more dynamic forms in administrate, though I'm not certain. 

Check out the `belongs_to` relationship (assuming that a play belongs to a single theatre): http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association

Theatres will probably _have many_ plays through a `has_many` relationship

**Comment by youcatastrophe** [comment]
That was my bad. I _did_ have some ActiveRecord Associations set up, but I had forgot to push them. That said, it still wasn't working at all. But I think I may have used the wrong type of Assocations. I'll give it another go.

**Comment by youcatastrophe** [comment]
I've added a "has_many" Assocation to my Play Model. But I'm still not having any luck getting theater names to show up anywhere the theater_id is referenced. Unsure how to change the play_dashboard.rb file in the correct manner.

**Comment by youcatastrophe** [comment]
`ATTRIBUTE_TYPES = {
    id: Field::Number,
    title: Field::String,
    theater_id: Field::Number,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }`

For instance, in the above example, would I remove `theater_id` entirely and replace it with `theater.name`? I've tried this and it does not seem to be working.

**Comment by halfghaninne** [comment]
I just went through it in my rails playground and it seemed to be a good solution. Let me know if you hit any road bumps or if creating the association is not clear.

**Comment by halfghaninne** [comment]
I just went through adding an association in my rails playground and it seemed to be a good solution. Let me know if you hit any road bumps or if creating the association is not clear.

What file are you referencing above? You should not be altering the dashboard files. This has to do with db migrations and models.

**Comment by halfghaninne** [comment]
Please link in Slack if you have follow up questions! I may not see them here.

**Comment by youcatastrophe** [comment]
Thanks for the checking back in. I guess I don't know how we'd be able to accomplish this _without_ at least in some way modifying the Dashboard files.

**Comment by halfghaninne** [comment]
http://administrate-prototype.herokuapp.com/adding_custom_field_types

**Pull request merged**
