### PR TITLE
Nom ballot backend

### PR DESCRIPTION
**Pull request by mel-d**
My question is regarding line 10 of the nominations_controller (it'll eventually affect line 12 as well). I have a form where the fields were generated dynamically, and I'm struggling with how to save the params of a text field when the params would include a variable. I've done lots of Googling but must not be searching with the right vocab

### CODE REVIEW

**Comment by halfghaninne** [comment]
Hm! Can you please try moving your `binding.pry` before line 10 and then take a look at `params`, copy-pasting it here if possible?

**Comment by mel-d** [comment]
I'm actually getting an error because of the way I have line 10 written, so the binding.pry line didn't even activate--but before params were all returning nil! I'm assuming it's due to not having the params named the same as the names of each text field.

**Comment by halfghaninne** [comment]
If you move `binding.pry` before line 10, it should be triggered.

**Comment by mel-d** [comment]
No luck--it looks like it skips over the binding.pry because the error is so obnoxious

**Comment by mel-d** [comment]
I'll go edit the @ out of the params totally and just return whatever I get in that situation

**Comment by mel-d** [comment]
"authenticity_token"=>
  "xyEABT4sTkxqsPLwjgzZHFgRndKyKp3oQ6MqGaKud3/hr3g2vZ9PwcgbJ3lqCvdPN4GG9OGe693Vo6uKQVfPJg==",
 "theater1_1"=>"1",
 "show1_1"=>"1",
 "performer1_1"=>"Bill",
 "role1_1"=>"Nye",
 "theater2_1"=>"",
 "show2_1"=>"",
 "performer2_1"=>"",
 "role2_1"=>"",
 "theater3_1"=>"",
 "show3_1"=>"",
 "performer3_1"=>"",
 "role3_1"=>"",
 "controller"=>"nominations",
 "action"=>"save_nominee"}

**Comment by mel-d** [comment]
So this is when I changed line 10 to say params[:nominee1_1] instead of any sort of dynamic variable.

**Comment by halfghaninne** [comment]
Thank you! Taking a closer look now.

**Pull request merged**
