### PR TITLE
creating new html and css for new view dup check page #102

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
im getting this error message a lot when trying to view the homepage or logout

Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( static_pages.css )` to `config/initializers/assets.rb` and restart your server

Extracted source (around line #14):

  <%= stylesheet_link_tag params[:controller] %>

should i run this code it suggests?

**Comment by sumeetjain** [comment]
Did you add this line of code yourself? `<%= stylesheet_link_tag params[:controller] %>`? Or was it built into the framework I gave you?

**Comment by clburns107** [comment]
I did not add it. But i do not know if it was built in or if someone else put it there... Im assuming it was built in?

**Comment by sumeetjain** [comment]
For now, go ahead and add it. It's not going to harm anything. But we'll do some refactoring later.

**Comment by clburns107** [comment]
Looks like that line of code already exists in the file its telling me to add it to.

**Comment by sumeetjain** [comment]
How about deleting `<%= stylesheet_link_tag params[:controller] %>`?

**Comment by clburns107** [comment]
Seems to have worked :+1:

**Pull request merged**
