### PR TITLE
86 nominations links

### PR DESCRIPTION
**Pull request by santaclauslives**
Want to add functional links to html of nominations page to replace the placeholder links that are there now.

### CODE REVIEW

**Comment by sumeetjain** [comment]
Are you looking for how to add the correct paths (as values for the `href` attributes) for these links?

**Comment by santaclauslives** [comment]
yes. Both how to add the correct paths and, if Mel has already done a form that takes in a nomination, what the paths are. (Maybe she is doing something else.)

**Comment by sumeetjain** [comment]
That's something that should be a very quick conversation with your team. They will know what the paths to a particular page are.

You can also look in **config/routes.rb**, as all of the routes in a Rails app are defined there.

**Comment by sumeetjain** [comment]
However, now that I think about it... Why are you linking to an award? What is that award page supposed to show?

**Comment by santaclauslives** [comment]
I may have this completely screwed up, but I am not linking to an award, I am at least theoretically linking to a page where you would nominate somebody for the award named on the link. With the number of categories and up to 5 nominations per category I didn't see that working on just this one nominations page, so I made dropdowns with links for each category for which somebody can be nominated.  So there might be "nominations/1" and "nominations/2" or there might be "nominations/musicals/lead_actor" and so on. But there's probably a better way. Maybe it can all be done on this one page with a very long page and just links to difference points on the page.

**Comment by sumeetjain** [comment]
> Maybe it can all be done on this one page with a very long page and just links to difference points on the page.

Let's do that, at least for now.

But if you _were_ to execute your idea, you would expect your back-end folks to build you the pages you're talking about. It's possible those pages just don't exist, so linking to them is impossible.

Even if the pages don't exist, if you wanted to build the front-end for them, you could do that. You would just use placeholders for the content of the eventual page.

**Comment by santaclauslives** [comment]
Thanks Sumeet. There is something called nomination_ballot on the routes page, and a controller action for it. Just to make sure I'm not duplicating something Melinda is working on, I'll check with her.

**Comment by santaclauslives** [comment]
Man that is some ugly html code. Very repetitive. There must be a ruby way to do this. More to the point, my drop downs are not dropping down.

**Comment by sumeetjain** [comment]
Usually we'd use the `<select>` tag for dropdowns. I don't see any in your code. Is there some other kind of dropdown functionality you're trying to achieve?

**Comment by santaclauslives** [comment]
I was following an instruction set from w3 schools. Had no other goal except to make a dropdown menu appear on hover. I am not married to the idea of having hover be the triggering event. Just function.

**Comment by sumeetjain** [comment]
Gotcha. For now, any advanced functionality like that should be deferred. Just HTML for now. And in HTML, we use the `select` tag, so please use that for the page in question.

**Pull request merged**
